# Taking latest version of Tomcat
FROM Tomcat : latest
# RUN the 
 cp -R /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps 
# Copy the
 current path of tomcat
COPY ./*.war /usr/local/tomcat/webapps
